/*
    Generated by Since.Versioning, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8b3c12f388b1d179
        from C:\Users\Tim Rawlinson\Documents\Visual Studio 2015\Projects\Since\Since.Immutable\Properties\AssemblyInfo.cs
*/
using System.Reflection;

[assembly: AssemblyVersion("0.1.0.7368")]
[assembly: AssemblyFileVersion("0.1.0.7368")]
[assembly: AssemblyInformationalVersion("0.1.0+dev.7368.mod (git.82bf5916)")]
